#    Copyright 2020 by Brett J. Moan
#
#    This file is part of pyautoeios.
#
#    pyautoeios is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    pyautoeios is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with pyautoeios.  If not, see <https://www.gnu.org/licenses/>.
import collections

THook = collections.namedtuple("THook", "cls field desc multiplier")


def hook(c: str, f: str, d: str, m: int):
    return THook(c.encode("utf8"), f.encode("utf8"), d.encode("utf8"), m)


ACTOR_ISWALKING = hook("dr", "an", "Z", 1)
ACTOR_COMBATINFOLIST = hook("dr", "cl", "Loc;", 1)
ACTOR_SPOTANIMATION = hook("dr", "dy", "I", 1999731983)
ACTOR_SPOTANIMATIONFRAME = hook("N/A", "N/A", "N/A", 1)
ACTOR_SPOTANIMATIONFRAMECYCLE = hook("dr", "dh", "I", 136905603)
ACTOR_GRAPHICSID = hook("N/A", "N/A", "N/A", 1)
ACTOR_HEIGHT = hook("dr", "df", "I", -610695377)
NPCDEFINITION_ID = hook("hw", "ai", "I", -1243106285)
NPCDEFINITION_NAME = hook("hw", "az", "Ljava/lang/String;", 1)
NPCDEFINITION_ACTIONS = hook("hw", "bv", "[Ljava/lang/String;", 1)
NPCDEFINITION_MODELIDS = hook("hw", "aa", "[I", 1)
NPCDEFINITION_COMBATLEVEL = hook("hw", "bd", "I", 989486243)
NPCDEFINITION_VISIBLE = hook("hw", "bm", "Z", 1)
NPCDEFINITION_MODELCACHE = hook("hw", "ac", "Lle;", 1)
NPCDEFINITION_TRANSFORMATIONS = hook("hw", "bl", "[I", 1)
NPCDEFINITION_MODELTILESIZE = hook("hw", "ap", "I", -733591527)
NPCDEFINITION_MODELSCALEWIDTH = hook("hw", "by", "I", 1754811063)
NPCDEFINITION_MODELSCALEHEIGHT = hook("hw", "bs", "I", -183655351)
NPC_DEFINITION = hook("dx", "au", "Lhw;", 1)
PLAYERDEFINITION_NPCTRANSFORMID = hook("mt", "ai", "I", -1253753061)
PLAYERDEFINITION_ISFEMALE = hook("mt", "af", "Z", 1)
PLAYERDEFINITION_ANIMATEDMODELID = hook("mt", "az", "J", -4990962188091480033)
PLAYERDEFINITION_MODELID = hook("mt", "ap", "J", 8032241556888834061)
PLAYERDEFINITION_EQUIPMENT = hook("mt", "ae", "[I", 1)
PLAYERDEFINITION_MODELCACHE = hook("mt", "am", "Lle;", 1)
PLAYER_NAME = hook("df", "au", "Luc;", 1)
PLAYER_MODEL = hook("df", "ab", "Ljr;", 1)
PLAYER_ISHIDDEN = hook("df", "aj", "Z", 1)
PLAYER_DEFINITION = hook("df", "ae", "Lmt;", 1)
PLAYER_COMBATLEVEL = hook("df", "az", "I", 424288465)
PLAYER_INDEX = hook("df", "aw", "I", 1857589841)
PLAYER_ISANIMATING = hook("df", "as", "Z", 1)
OBJECTDEFINITION_ID = hook("hv", "aa", "I", 1130646297)
OBJECTDEFINITION_ANIMATIONID = hook("hv", "aw", "I", -671344969)
OBJECTDEFINITION_DEFINITIONCACHE = hook("hv", "at", "Lle;", 1)
OBJECTDEFINITION_MODELCACHE = hook("hv", "az", "Lle;", 1)
OBJECTDEFINITION_MODELIDS = hook("hv", "af", "[I", 1)
OBJECTDEFINITION_MODELS = hook("hv", "ad", "[I", 1)
OBJECTDEFINITION_NAME = hook("hv", "aq", "Ljava/lang/String;", 1)
OBJECTDEFINITION_ACTIONS = hook("hv", "bk", "[Ljava/lang/String;", 1)
OBJECTDEFINITION_TRANSFORMATIONS = hook("hv", "bb", "[I", 1)
OBJECTDEFINITION_TRANSFORMATIONVARBIT = hook("hv", "br", "I", -549604083)
OBJECTDEFINITION_TRANSFORMATIONVARP = hook("hv", "be", "I", 244969535)
WIDGETNODE_ID = hook("ds", "au", "I", 2086760251)
WIDGET_NAME = hook("mi", "gp", "Ljava/lang/String;", 1)
WIDGET_TEXT = hook("mi", "de", "Ljava/lang/String;", 1)
WIDGET_WIDGETID = hook("mi", "bp", "I", -802277715)
WIDGET_PARENTID = hook("mi", "cr", "I", 1049113007)
WIDGET_PARENT = hook("mi", "ex", "Lmi;", 1)
WIDGET_ITEMID = hook("mi", "gq", "I", 1710253055)
WIDGET_ITEMIDS = hook("mi", "ga", "[I", 1)
WIDGET_STACKSIZES = hook("N/A", "N/A", "N/A", 1)
WIDGET_ITEMAMOUNT = hook("mi", "gt", "I", 1666268347)
WIDGET_SPRITEID = hook("mi", "ct", "I", 1694560891)
WIDGET_TEXTUREID = hook("mi", "cy", "I", -329704335)
WIDGET_ACTIONS = hook("N/A", "N/A", "N/A", 1)
WIDGET_ACTIONTYPE = hook("mi", "bb", "I", 2112192689)
WIDGET_TYPE = hook("mi", "bo", "I", -1370156439)
WIDGET_ISHIDDEN = hook("mi", "cd", "Z", 1)
WIDGET_ABSOLUTEX = hook("mi", "bn", "I", 1356456497)
WIDGET_ABSOLUTEY = hook("mi", "bw", "I", -1035953241)
WIDGET_RELATIVEX = hook("mi", "cw", "I", 979552283)
WIDGET_RELATIVEY = hook("mi", "cf", "I", -1112610033)
WIDGET_SCROLLX = hook("mi", "ce", "I", -739875643)
WIDGET_SCROLLY = hook("mi", "cq", "I", 595666453)
WIDGET_WIDTH = hook("mi", "cm", "I", 501302871)
WIDGET_HEIGHT = hook("mi", "cn", "I", 1553685319)
WIDGET_CHILDREN = hook("mi", "gn", "[Lmi;", 1)
WIDGET_BOUNDSINDEX = hook("mi", "hk", "I", 1527386271)
WIDGET_WIDGETCYCLE = hook("mi", "hz", "I", -822322021)
ITEMDEFINITION_ID = hook("hn", "an", "I", -466945669)
ITEMDEFINITION_NAME = hook("hn", "ab", "Ljava/lang/String;", 1)
ITEMDEFINITION_ISMEMBERS = hook("hn", "bs", "Z", 1)
ITEMDEFINITION_GROUNDACTIONS = hook("hn", "bm", "[Ljava/lang/String;", 1)
ITEMDEFINITION_ACTIONS = hook("hn", "bf", "[Ljava/lang/String;", 1)
ITEMDEFINITION_CACHE = hook("hn", "af", "Lle;", 1)
ITEM_ID = hook("ed", "au", "I", 943663449)
ITEM_STACKSIZES = hook("ed", "ae", "I", -2002661055)
ITEMNODE_ITEMIDS = hook("dd", "ae", "[I", 1)
ITEMNODE_ITEMQUANTITIES = hook("dd", "ao", "[I", 1)
ITEMNODE_CACHE = hook("dd", "au", "Lso;", 1)
LOGIN_XPADDING = hook("cy", "ao", "I", 657439907)
LOGIN_BOXXOFFSET = hook("cy", "ay", "I", -390756021)
LOGIN_LOADINGPERCENT = hook("cy", "av", "I", -427966603)
LOGIN_ACCOUNTSTATUS = hook("cy", "bi", "I", -1116009889)
LOGIN_INDEX = hook("cy", "cw", "I", 1467944731)
LOGIN_BUTTONSPRITE = hook("it", "ai", "Luk;", 1)
LOGIN_USERNAME = hook("cy", "cx", "Ljava/lang/String;", 1)
LOGIN_PASSWORD = hook("cy", "cr", "Ljava/lang/String;", 1)
LOGIN_CURSORFIELD = hook("cy", "dh", "I", -1433824975)
VARPS_MASKS = hook("mz", "au", "[I", 1)
VARPS_MAIN = hook("mz", "ao", "[I", 1)
VARCS_MAP = hook("ej", "at", "Ljava/util/Map;", 1)
VARCS_STRINGS = hook("ej", "ac", "[Ljava/lang/String;", 1)
VARCS_VARCMAP = hook("ej", "at", "Ljava/util/Map;", 1)
VARBITDEFINITION_CACHE = hook("hb", "ae", "Lle;", 1)
VARBITDEFINITION_BASE = hook("hb", "ao", "I", 144903653)
VARBITDEFINITION_STARTBIT = hook("hb", "at", "I", 225410143)
VARBITDEFINITION_ENDBIT = hook("hb", "ac", "I", 1882806955)
CLIENT_REVISION = hook("uy", "ao", "I", -671342643)
CLIENT_CLIENT = hook("it", "bw", "Lclient;", 1)
CLIENT_LOCALNPCS = hook("client", "ij", "[Ldx;", 1)
CLIENT_NPCINDICES = hook("client", "ih", "[I", 1)
CLIENT_NPCCOUNT = hook("client", "in", "I", 641541081)
CLIENT_LOCALPLAYERS = hook("client", "mi", "[Ldf;", 1)
CLIENT_PLAYERINDICES = hook("ee", "az", "[I", 1)
CLIENT_PLAYERCOUNT = hook("ee", "ai", "I", 2110833449)
CLIENT_LOCALPLAYER = hook("hb", "mo", "Ldf;", 1)
CLIENT_PLAYERINDEX = hook("client", "mx", "I", 530420265)
CLIENT_LOOPCYCLE = hook("client", "eh", "I", 522278027)
CLIENT_GAMESTATE = hook("client", "dj", "I", -667400491)
CLIENT_LOGINSTATE = hook("client", "gi", "I", 1808720373)
CLIENT_ISLOADING = hook("N/A", "N/A", "N/A", 1)
CLIENT_CROSSHAIRCOLOR = hook("client", "mj", "I", 1950062223)
CLIENT_ANIMATIONFRAMECACHE = hook("ib", "aa", "Lle;", 1)
CLIENT_GROUNDITEMS = hook("client", "nr", "[[[Low;", 1)
CLIENT_COLLISIONMAPS = hook("client", "jz", "[Lis;", 1)
CLIENT_TRADINGPOSTOFFERS = hook("client", "wf", "[Loh;", 1)
CLIENT_CAMERAX = hook("hw", "kk", "I", 757716957)
CLIENT_CAMERAY = hook("fr", "km", "I", 1907020251)
CLIENT_CAMERAZ = hook("fl", "kc", "I", 912731593)
CLIENT_CAMERAPITCH = hook("ep", "kz", "I", 1065394883)
CLIENT_CAMERAYAW = hook("ef", "kh", "I", 1799410691)
CLIENT_REGION = hook("fh", "jb", "Liv;", 1)
CLIENT_ISREGIONINSTANCED = hook("client", "jp", "Z", 1)
CLIENT_REGIONINSTANCES = hook("N/A", "N/A", "N/A", 1)
CLIENT_PLANE = hook("dm", "mn", "I", 1873768041)
CLIENT_BASEX = hook("ev", "je", "I", 1638537919)
CLIENT_BASEY = hook("bx", "jr", "I", 1819265849)
CLIENT_DESTINATIONX = hook("client", "tz", "I", 850793817)
CLIENT_DESTINATIONY = hook("client", "ti", "I", -214324647)
CLIENT_SINE = hook("ix", "at", "[I", 1)
CLIENT_COSINE = hook("ix", "ac", "[I", 1)
CLIENT_TILEHEIGHTS = hook("du", "au", "[[[I", 1)
CLIENT_TILESETTINGS = hook("du", "ae", "[[[B", 1)
CLIENT_ITEMNODECACHE = hook("dd", "au", "Lso;", 1)
CLIENT_WIDGETS = hook("ly", "ak", "[[Lmi;", 1)
CLIENT_GAMESETTINGS = hook("mz", "ao", "[I", 1)
CLIENT_WIDGETNODECACHE = hook("client", "pu", "Lso;", 1)
CLIENT_WIDGETPOSITIONX = hook("client", "rt", "[I", 1)
CLIENT_WIDGETPOSITIONY = hook("client", "rx", "[I", 1)
CLIENT_WIDGETWIDTHS = hook("client", "rw", "[I", 1)
CLIENT_WIDGETHEIGHTS = hook("client", "rn", "[I", 1)
CLIENT_VALIDWIDGETS = hook("mq", "bh", "[Z", 1)
CLIENT_WIDGETROOTINTERFACE = hook("client", "pj", "I", 1642683045)
CLIENT_VIEWPORTWIDTH = hook("client", "vo", "I", -685574095)
CLIENT_VIEWPORTHEIGHT = hook("client", "vn", "I", -212965565)
CLIENT_VIEWPORTSCALE = hook("client", "vx", "I", -544120667)
CLIENT_MAPANGLE = hook("client", "lx", "I", -817936455)
CLIENT_MAPSCALE = hook("N/A", "N/A", "N/A", 1)
CLIENT_MAPOFFSET = hook("N/A", "N/A", "N/A", 1)
CLIENT_MENUCOUNT = hook("client", "om", "I", 1676985473)
CLIENT_MENUACTIONS = hook("client", "ob", "[Ljava/lang/String;", 1)
CLIENT_MENUOPTIONS = hook("client", "ok", "[Ljava/lang/String;", 1)
CLIENT_ISMENUOPEN = hook("client", "nf", "Z", 1)
CLIENT_MENUX = hook("al", "no", "I", 457066205)
CLIENT_MENUY = hook("qf", "nx", "I", 183418913)
CLIENT_MENUWIDTH = hook("mq", "nh", "I", 617707969)
CLIENT_MENUHEIGHT = hook("jn", "nc", "I", 1693604393)
CLIENT_ISRESIZABLE = hook("client", "sd", "Z", 1)
CLIENT_CURRENTLEVELS = hook("client", "ny", "[I", 1)
CLIENT_REALLEVELS = hook("client", "nk", "[I", 1)
CLIENT_EXPERIENCES = hook("client", "nj", "[I", 1)
CLIENT_CURRENTWORLD = hook("client", "bg", "I", -831561099)
CLIENT_ENERGY = hook("client", "px", "I", 2106479597)
CLIENT_WEIGHT = hook("client", "pt", "I", 679999119)
CLIENT_ISITEMSELECTED = hook("client", "ov", "I", 61632949)


### Hooks brandon doesn't have
CLEAR_LOGIN_SCREEN = hook("cj", "b", "Z", 1)
CURRENT_LOGIN_FIELD = hook("cj", "bp", "I", -1450671401)
HOVERED_WORLD_INDEX = hook("cj", "by", "I", -374959449)
LOGIN_BOX_X = hook("cj", "w", "I", -1076468107)
LOGIN_INDEX = hook("cj", "au", "I", 1682315035)
LOGIN_LOADING_PERCENT = hook("cj", "d", "I", -1330731251)
LOGIN_LOADING_TEXT = hook("cj", "a", "Ljava/lang/String;", 1)
LOGIN_PASSWORD = hook("cj", "an", "Ljava/lang/String;", 1)
LOGIN_RESPONSE0 = hook("cj", "ai", "Ljava/lang/String;", 1)
LOGIN_RESPONSE1 = hook("cj", "ax", "Ljava/lang/String;", 1)
LOGIN_RESPONSE2 = hook("cj", "ag", "Ljava/lang/String;", 1)
LOGIN_RESPONSE3 = hook("cj", "aq", "Ljava/lang/String;", 1)
LOGIN_USERNAME = hook("cj", "aw", "Ljava/lang/String;", 1)
WORLD_SELECT_OPEN = hook("cj", "bl", "Z", 1)
WORLD_SELECT_PAGE = hook("cj", "bq", "I", -1738897563)
WORLD_SELECT_PAGES_COUNT = hook("cj", "bv", "I", 1533348533)
LOGIN_X_PADDING = hook("cj", "l", "I", 1744707789)
